///$tab Main
SET ThousandSep=',';
SET DecimalSep='.';
SET MoneyThousandSep=',';
SET MoneyDecimalSep='.';
SET MoneyFormat='$#,##0.00;-$#,##0.00';
SET TimeFormat='h:mm:ss TT';
SET DateFormat='M/D/YYYY';
SET TimestampFormat='M/D/YYYY h:mm:ss[.fff] TT';
SET FirstWeekDay=6;
SET BrokenWeeks=1;
SET ReferenceDay=0;
SET FirstMonthOfYear=1;
SET CollationLocale='en-US';
SET CreateSearchIndexOnReload=1;
SET MonthNames='Jan;Feb;Mar;Apr;May;Jun;Jul;Aug;Sep;Oct;Nov;Dec';
SET LongMonthNames='January;February;March;April;May;June;July;August;September;October;November;December';
SET DayNames='Mon;Tue;Wed;Thu;Fri;Sat;Sun';
SET LongDayNames='Monday;Tuesday;Wednesday;Thursday;Friday;Saturday;Sunday';

///$tab Load data
// Data from Kaggle: https://www.kaggle.com/kemical/kickstarter-projects

Kickstarter:
LOAD
    ID,
    name,
    category,
    main_category,
    currency,
    Date(deadline, 'YYYY-MM-DD') as deadline,
    goal,
    Date(launched, 'YYYY-MM-DD') as launched,
    pledged,
    state,
    backers,
    country,
    "usd pledged"
//     usd_pledged_real
FROM [lib://Test data/kickstarter/ks-projects-201801.csv]
(txt, codepage is 28591, embedded labels, delimiter is ',', msq)
Where
  Date(deadline, 'YYYY-MM-DD') > '2009-01-01' and
  Date(launched, 'YYYY-MM-DD') > '2009-01-01'

;



Sleep 60000;
